### ISSUE TITLE
[Suggestion] Include credits to Developers Community

### ISSUE THREAD

**Issue by cesarsicas** [mobile-roadmap/android-developer-roadmap#2]
Hi ! Was this Roadmap based on that research posted on AndroidDevBr  slack ? 
If it is correct, should be included credits to the Android Dev Comunnity too, not only two authors. 

Anyway, thanks for the Roadmap, it will be very useful !

**Comment by drcabral** [comment]
Hi @cesarsicas !

Thanks for your suggestion! Yes, it is the same roadmap developed with the research that we shared on multiple channels. We will include this credits to the developers community.

Thank you.
