### ISSUE TITLE
Suggestion: add CI/CD systems and tools

### ISSUE THREAD

**Issue by punksta** [mobile-roadmap/android-developer-roadmap#24]
I think it's important to know how to use ci for testing, building and publication, especially if you are working in a team.

## tools/libs
1. https://fastlane.tools/  - set of cli tools for mobile development automation
2. https://github.com/Triple-T/gradle-play-publisher - publish apk and metadata from gradle tasks
3. https://firebase.google.com/docs/test-lab/android/continuous - cloud testing

## ci/cd software 
1. https://travis-ci.org/ cloud base
2. https://circleci.com/ cloud base
3. https://docs.gitlab.com/ee/ci/README.html cloud/self-hosted base
4. https://jenkins.io/ - self-hosted
5. https://www.jetbrains.com/teamcity/ - self-hosted/cloud

**Comment by drcabral** [comment]
Hey @punksta , thanks for your suggestion!

What do you think to include CI/CD box in "also nice to know" section?

**Comment by punksta** [comment]
`also nice to know` sounds good.

**Comment by TWiStErRob** [comment]
https://github.com/features/actions
