### ISSUE TITLE
Suggestions after attend AndroidFestBH talk

### ISSUE THREAD

**Issue by nglauber** [mobile-roadmap/android-developer-roadmap#25]
Hey folks,

First of all, thanks for this awesome work. The Android community was claiming this for a long time. 
Well, after attend your talk at the AndroidFestBH I would like to suggest these changes/fixes on the roadmap:

- XML ​​is a markup language (not a programming language), I would recommend to move to somewhere else like "File formats" and put it there with JSON standard.
- In accordance with the Android web-site the four App Components are: Activities, Services, Broadcast Receivers and Services (https://developer.android.com/guide/components/fundamentals). My suggestion would be move Fragments to the User Interface section.
- I can't see Notifications Block connected to anywhere. I think it can be moved to User interface section.
- imho ListView and GridView are not layouts, they are ViewGroup's. My suggestion would be add a "Data Views" section (or something) and  put ListView, Spinner, RecyclerView there under UIComponents section.
- Spinner is a AdapterView, so it should be under the UI Components> AdapterView section (or to the section I mentioned above).
- Under tests section, would it be "Smoke Tests" instead of "Somke Tests"?
- All architectures under "Architecture> Code Architecture", are standards to organize the presentation layer. My suggestions would be change to "Presentation Architecture", "Presentation Patterns" or something similar.
- I would remove Volley under networking and add the "Data Transfer Format" (or something similar) and put REST, GraphQL, Protocol Buffer and FlatBuffer.
- AndroidX and Jetpack is the same thing, so I would remove AndroidX box.
- It would be nice to have a reference for each jetpack component from its respective topic. Eg: SQLite -> Room, MVVM -> View Model, Services -> WorkManager, Activity / Fragment Lifecycle -> Lifecycle (this is missing). So, I think it's better to spread the components along the graph than centralize them in a single section.
- Under Security, add R8.
- Move (or put a reference to) Animated Vector Drawables to Animation section.

Thanks in advance ;)

**Comment by drcabral** [comment]
Hi @nglauber , thank you so much for the insights! We will take a look into each point to improve our roadmap.

One doubt about the **Presentation Patterns**: the suggestion here is put all of the architectures that aims to organize the presentation layer under this macro or just reply them to this as a new micro content box? I see value in show some possibilities about architectures in the current granularity and point which one is recommended or most used nowadays, but we can discuss about it!

**Comment by drcabral** [comment]
Hey @nglauber 

I did some of the changes that you suggested. I only need to understand better the suggestion about **Presentation Patterns** to apply it and also left the **reference for each jetpack components** (that i'll do later today i guess). 

Would be nice if you could review the Pull request as well :)

Thanks a lot!

**Comment by nglauber** [comment]
hi @drcabral,
I'm glad that my suggestions were useful. 👏 

Let me change my comment about *presentation patterns* a little. I would suggest to add the "Clean Architecture" to the list, but I'm not sure if it's good idea to put it in the same bucket of the other patterns. I'm saying that because the Clear Architecture mention this in the _[Interface adapters layers](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)_ section:
> It is this layer, for example, that will wholly contain the MVC architecture of a GUI. The Presenters, Views, and Controllers all belong in here. 

Once MVP and MVVM are variants/evolutions of the MVC pattern, maybe we can have something like:
- Architecture > Project > Clean Architecture
- Architecture > Presentation > MVP / MVVM / MVC (I've never used MVI and VIPER, not sure if they fits here...)
It makes more sense to me. :)

Let me know if I was not clear enough.
Best regards.
