### ISSUE TITLE
Create new section " Roadmap study Content" in Spanish roadmap readme version

### ISSUE THREAD

**Issue by drcabral** [mobile-roadmap/android-developer-roadmap#41]
Now we have "Roadmap study Content" section that point to a new file that we will fill with reading suggestion, courses, etc, about our roadmap. You can add this section, pointing to the same file, in Spanish language.

**Comment by LuisFerTR** [comment]
I would like to work on this

**Comment by asaikarthikeya** [comment]
@drcabral  Any updates???? #51
