### ISSUE TITLE
Suggest Android Roadmap topic contents in our new contents file

### ISSUE THREAD

**Issue by drcabral** [mobile-roadmap/android-developer-roadmap#43]
Suggest content to our community study and know more about Android! Can be courses, articles, etc, in our new contents file that you can found here:

[Contents File](https://github.com/mobile-roadmap/android-developer-roadmap/blob/master/ROADMAP_STUDY_CONTENT.md)

**Comment by Dabjazz** [comment]
I would like to contribute to this project!

**Comment by drcabral** [comment]
Feel free to do it! We would love to receive your contribution!

**Comment by asaikarthikeya** [comment]
I am willing to contribute to this. How do i get started.

Thank you.

**Comment by anacoimbrag** [comment]
@asaikarthikeya you are welcome to do so! You can add relevant study topics and content in our new [file](https://github.com/mobile-roadmap/android-developer-roadmap/blob/master/ROADMAP_STUDY_CONTENT.md).

**Comment by asaikarthikeya** [comment]
@anacoimbrag 
Happy to receive a quick response :)
I have few Questions -

1. Video  resources section is done right? Can i suggest few more resources if possible? 
2. The empty sections like Android Studio,App Manifest and so on should be the filled up with good resources(Both 
    videos and blogs) available on the Internet ?

**Comment by anacoimbrag** [comment]
@asaikarthikeya awesome! We are happy that you want to contribute!
1. Yes, please suggest as many resources as you can 😊
2. Definitely!

**Comment by asaikarthikeya** [comment]
@anacoimbrag 

#47 Please review and Update me if any modification needed.
