### ISSUE TITLE
[Suggestion] Include "Clean Architecture"

### ISSUE THREAD

**Issue by andproger** [mobile-roadmap/android-developer-roadmap#9]
Hello! Thank you for roadmap, i liked)
I propose to add Clean Architecture.
MVP or MVI or ... - is only presentation layer. 
Understanding design for all layers of application is really important for android developer.

**Comment by drcabral** [comment]
Hey @andproger , thanks for the feedback!

I think that there is many ways to apply clean architecture in the listed architectures. For example, `VIPER` is a clean architecture based one and nowadays there is an implementation of `MVVM` that implements use cases in its structure.

So, maybe we can add a note or something like this to specify that these architectures have a clean architecture approach.

Do you like this suggestion? Do you have another one?

**Comment by andproger** [comment]
Thanks.

I think that it is good to add a note and a separate section. Most projects have a clean architecture, be it in Viper, MVVM or any combination (Clean architecture + presentation architecture). It seems to me that when studying architectures with clean architecture you need to get acquainted separately.

**Comment by drcabral** [comment]
Humm, yes, we can add an "transversal good to know things" (with a better name), and then we can put things like this. 

In the next days we will work on improvements and Ill consider your suggestion.

thanks

**Comment by anacoimbrag** [comment]
Closed in #32
